api:
  insecure: true
  dashboard: true
  # Remarque: Traefik v2 ne supporte pas la personnalisation du dashboard via 'customizations'.

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  consulCatalog:
    endpoint:
      address: "consul:8500"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# Métriques et monitoring
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true

# Logs détaillés
log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: keep
        Authorization: drop
        Content-Type: keep

# Tracing pour le debugging
tracing:
  jaeger:
    samplingServerURL: http://jaeger:14268/api/sampling
    localAgentHostPort: jaeger:6831

# Configuration globale
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Health check pour Traefik lui-même
ping:
  entryPoint: "web"
