api:
  insecure: true
  dashboard: true
  debug: true
  # Personnalisation du dashboard
  customizations:
    # Titre personnalisé
    title: "TUVCB Monitoring Hub"
    # CSS personnalisé pour ajouter des liens
    css: |
      .monitoring-links {
        position: fixed;
        top: 10px;
        right: 10px;
        z-index: 1000;
        background: rgba(0,0,0,0.8);
        padding: 10px;
        border-radius: 5px;
      }
      .monitoring-links a {
        color: #00d4ff;
        text-decoration: none;
        margin: 0 10px;
        padding: 5px 10px;
        border: 1px solid #00d4ff;
        border-radius: 3px;
        display: inline-block;
        margin-bottom: 5px;
      }
      .monitoring-links a:hover {
        background: #00d4ff;
        color: #000;
      }

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  consulCatalog:
    endpoint:
      address: "consul:8500"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# Métriques et monitoring
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true

# Logs détaillés
log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: keep
        Authorization: drop
        Content-Type: keep

# Tracing pour le debugging
tracing:
  jaeger:
    samplingServerURL: http://jaeger:14268/api/sampling
    localAgentHostPort: jaeger:6831

# Configuration globale
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Health check pour Traefik lui-même
ping:
  entryPoint: "traefik"
